kind: Secret
apiVersion: v1
metadata:
  name: ${DATABASE_SERVICE_NAME}
  annotations:
    template.openshift.io/expose-database_name: "{.data['database-name']}"
    template.openshift.io/expose-password: "{.data['database-password']}"
    template.openshift.io/expose-username: "{.data['database-user']}"
stringData:
  database-name: ${POSTGRESQL_DATABASE}
  database-password: ${POSTGRESQL_PASSWORD}
  database-user: ${POSTGRESQL_USER}
